### PR TITLE
Upgrade/angular 10

### PR DESCRIPTION
**Pull request by abdatta**
Updated angular and nx to version 10.
Steps done:
- ng update @angular/core @angular/cli
- ng update @angular/material
- ng update @nrwl/workspace

### CODE REVIEW

**Comment by abdatta** [comment]
Thanks @bohoffi for merging this. Can you please release the merged angular 10 version on npm? I would like to use it in one of my projects.

One more thing, can you please add "hacktoberfest" as a label on your repository? It'll make my pr count towards the hacktoberfest challenge.

Thank you :)

**Comment by bohoffi** [comment]
Sure I can do that @abdatta but I won't have the time until tomorrow if that's ok for you?

**Comment by abdatta** [comment]
Yup that's ok. Thanks!

**Comment by bohoffi** [comment]
Hey @abdatta,
I've published `v3.2.0`, added the `hacktoberfest` topic to the repo and labelled this PR with `hacktoberfest-accepted` ;)

**Comment by abdatta** [comment]
Awesome, thanks a lot! Lemme know if you need any help in future in any of the repos.

**Pull request merged**
