### PR TITLE
Add ability to provide sessionStorage

### PR DESCRIPTION
**Pull request by vladimirstempel**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

No ability to provide type of `Storage`.

Issue Number: N/A

## What is the new behavior?

Added `storage` parameter to provide `Storage` type.
Default type - `localStorage`.
Allowed types - `localStorage | sessionStorage`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

N/A

### CODE REVIEW

**Comment by bohoffi** [comment]
Hi @vladimirstempel, in general I can't find an reasons against this PR **but** this library started and evolved focussing on localstorage only - which includes all of the naming (repository, npm package, service, etc).

Including this PR would extend the focus of the library and an overall name change would be required to reflect it properly. Renaming the npm package will affect projects currently using this library when it comes to future bug fixes.
And this is something I didn't plan on doing.

**Comment by vladimirstempel** [comment]
@bohoffi Hi, but you don't need to rename library, it can be just additional feature for thoose who need it, anyway, by default it uses localStorage, so it doesn't affect to anything) I use your library, it's excellent one, but I need ability to use sessionStorage instead of localStorage.

**Comment by vladimirstempel** [comment]
Or you can make fork from this repo and create another npx-sessionstorage library)

**Comment by bohoffi** [comment]
If you don't mind - please give me some time to think about a proper way.

**Comment by vladimirstempel** [comment]
Ok, no problem😊

**Comment by bohoffi** [comment]
@vladimirstempel I've decided to include your changes into the library without changing the name.
I'll review this PR either today or tomorrow.

**Comment by vladimirstempel** [comment]
@bohoffi cool! Thanks a lot))

**Review by bohoffi — APPROVED** [review]

**Pull request merged**
